---

- name: Understanding precedent of vars
  hosts: all
  become: yes
    #vars:
    #USRN: playuser
    #COMM: variable for playbook
  tasks:
   - name: create a user
     user:
        name: "{{USRN}}"
        comment: "{{COMM}}"
     register: USROUT
   - debug:
       var: USROUT.name
   - debug:
       var: USROUT.comment

