
---
# tasks file for post-install
 - name: Install NTP
   yum:
      name: "{{item}}"
      state: present
   when: ansible_os_family == "RedHat"
   loop:
      - ntp
      - wget
      - git
      - zip
      - unzip


 - name: Install NTP on Ubuntu
   apt:
       name: ntp
       state: present
   when: ansible_distribution == "Ubuntu"

 - name: Start & enable NTP
   service:
       name: ntpd
       state: started
       enabled: yes

 - name: Add group
   group:
      name: devops
      state: present

 - name: Add user
   user:
      name: "{{item}}"
      state: present
      groups: devops
   loop: "{{usernames}}"

 - name: Banner file /etc/motd
   copy:
      content: "This {{ansible_distribution}} is Managed by Ansible. \n"
      dest: /etc/motd

 - name: Deploy NTP conf file
   template:
      src: ntp.conf.j2
      dest: "{{ntp_path}}"
   notify:
      - Restart NTP

 - name: Dir for dev data
   file:
      path: /opt/devdata
      state: directory
      mode: 0775
 - name: Deploy dev data file
   copy:
      src: dev.txt
      dest: /opt/devdata/dev.txt
